default_settings: null
behaviors:
  TANK:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048 
      buffer_size: 20480 
      learning_rate: 0.0003 
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 40
    checkpoint_interval: 1000000
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: false
env_settings:
  env_path: E:\UnityProject\MARLwork\5Rlvs5NR_drone_task_assignment\newwork\env\My project.exe
  env_args: null
  base_port: 4750
  num_envs: 8
  num_areas: 1
  seed: 42
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 2048
  height: 2048
  quality_level: 5
  time_scale: 4
  target_frame_rate: -1
  capture_frame_rate: 30
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: fly1104
  initialize_from: null
  load_model: false
  inference: false
  results_dir: E:\UnityProject\MARLwork\5Rlvs5NR_drone_task_assignment\newwork\result
torch_settings:
  device: cpu #option: cuda
debug: false
